"""The run notice: a local desktop notification saying the report exists.

`PRODUCT_SURFACES` 3.4 gives the push role to Firebase (owner decision D4). Firebase was never
built, and `DR-011` records why this fills that role instead: a LOCAL notification satisfies every
constraint 3.4 states, and satisfies them strictly harder than the mechanism 3.4 named. "Never
stores anything - no data leaves the machine" is literally true here, because nothing is sent
anywhere. There is no token, no third party, no retention surface, and no network call at all.

**What the notice may contain, and why the rule survives even locally.** The body is the run id and
a terminal status. Nothing else - no candidate count, no ticker, no decision word. 3.4's own reason
for that rule is privacy, which a local toast makes moot; the reason it is kept anyway is different
and it is the one that binds here: a glanceable summary is a summary the owner can ACT on without
opening the report, and this project has zero `validated` parameters. A notice reading "3
candidates, 1 Watch" would be a decision delivered without its provenance, its validation status,
or the standing warning the report carries - the exact thing `CHARTER` 4 and the Untested banner
exist to prevent. So the rule is not inherited from 3.4; it is re-earned.

That is enforced structurally rather than by review: `body()` takes the run id and the outcome and
has no other parameter, so there is no way to reach a `RunResult` from inside it, and a test pins
the rendered string against a fixed pattern.

Stdlib only, so gate 17 has nothing to catch and nothing can drift. The text reaches PowerShell
through the ENVIRONMENT, never interpolated into the script: a run id is generated by this codebase
and is not attacker-controlled, but building a shell command by string substitution is a habit that
is wrong exactly once.
"""

from __future__ import annotations

import os
import subprocess
from dataclasses import dataclass
from enum import StrEnum

#: Bounded so a hung notifier cannot stall the scheduled run. The notice is the LAST thing a run
#: does and the least important; the report is already on disk before this is called.
TIMEOUT_SECONDS = 15

#: PowerShell's own registered application id. Reused rather than registering one for SwingDesk,
#: because registering an AUMID writes to the user's registry - a system-settings change this
#: program has no business making to announce that a file exists.
_APP_ID = r"{1AC14E77-02E7-4E5D-B744-2EB1AE5198B7}\WindowsPowerShell\v1.0\powershell.exe"

#: Loading a WinRT type is ONE PowerShell statement and does not survive being wrapped - splitting
#: it to satisfy the line-length rule produced `At line:3 char:77` and a toast that never appeared.
#: Assembled here so the Python source stays short while PowerShell still receives a single line.
_LOAD_WINRT = (
    "[Windows.UI.Notifications.ToastNotificationManager, "
    "Windows.UI.Notifications, ContentType=WindowsRuntime] > $null"
)

_SCRIPT = f"""
$ErrorActionPreference = 'Stop'
{_LOAD_WINRT}
$template = [Windows.UI.Notifications.ToastNotificationManager]::GetTemplateContent(
    [Windows.UI.Notifications.ToastTemplateType]::ToastText02)
$nodes = $template.GetElementsByTagName('text')
$nodes.Item(0).AppendChild($template.CreateTextNode($env:SWINGDESK_NOTIFY_TITLE)) > $null
$nodes.Item(1).AppendChild($template.CreateTextNode($env:SWINGDESK_NOTIFY_BODY)) > $null
$toast = [Windows.UI.Notifications.ToastNotification]::new($template)
[Windows.UI.Notifications.ToastNotificationManager]::CreateToastNotifier(
    $env:SWINGDESK_NOTIFY_APPID).Show($toast)
"""

TITLE = "SwingDesk"


class Outcome(StrEnum):
    """A run's terminal state, as the owner needs to know it.

    Deliberately coarser than the decision vocabulary (`Trade`/`Watch`/`Skip`/`Pause`): this says
    whether to go and look, not what was found.
    """

    COMPLETE = "run complete"
    REFUSED = "run REFUSED"


@dataclass(frozen=True, slots=True)
class NotifyResult:
    """What happened, so the caller can report it rather than assume it."""

    delivered: bool
    detail: str


def body(run_id: str, outcome: Outcome) -> str:
    """The entire notice body. Two inputs, and there is deliberately no way to pass a third.

    This signature IS the content rule (see the module docstring). A future change that wants to
    add "and 3 candidates" has to add a parameter here, which is a visible act in review rather
    than a quiet interpolation somewhere in the caller.
    """
    return f"{outcome.value} - {run_id}. Report on disk."


def notify(run_id: str, outcome: Outcome) -> NotifyResult:
    """Raise a local desktop notification. Never raises, never blocks indefinitely.

    Returns rather than throwing because the notice is an OUTPUT of a run that has already
    finished and already written its report. A failure here must not change what the run decided,
    and must not change its exit code - `a.run_completes` counts runs that completed and produced a
    report, and both were true before this was called. The caller reports the failure loudly; see
    `cli.py`. Silence is the one thing this must never do, because unnoticed non-delivery is the
    defect this whole feature exists to close.
    """
    environment = {
        **os.environ,
        "SWINGDESK_NOTIFY_TITLE": TITLE,
        "SWINGDESK_NOTIFY_BODY": body(run_id, outcome),
        "SWINGDESK_NOTIFY_APPID": _APP_ID,
    }
    try:
        completed = subprocess.run(
            ["powershell.exe", "-NoProfile", "-NonInteractive", "-Command", _SCRIPT],
            capture_output=True, text=True, timeout=TIMEOUT_SECONDS, env=environment,
        )
    except FileNotFoundError:
        # Not Windows, or PowerShell absent. A fact about the machine, not a fault in the run.
        return NotifyResult(False, "powershell.exe not found on this machine")
    except subprocess.TimeoutExpired:
        return NotifyResult(False, f"the notifier did not return within {TIMEOUT_SECONDS}s")
    except OSError as error:
        return NotifyResult(False, f"could not start the notifier: {error}")

    if completed.returncode != 0:
        # The WHOLE message, collapsed - not its first line. PowerShell's first stderr line is
        # often just a position marker (`At line:3 char:77`), which says a failure happened and
        # nothing about what, and a diagnostic that omits the diagnosis is how a loud failure
        # becomes a quiet one.
        raw = (completed.stderr or completed.stdout or "").strip()
        detail = " ".join(raw.split())[:300]
        return NotifyResult(False, detail or "the notifier failed with no output")
    return NotifyResult(True, "delivered")
