"""Generate docs/01-requirements/FRD.md from registry/course_index.yml.

The functional requirements are the course's computable topics. Hand-transcribing 463 rows would
guarantee drift, so the FRD is generated from the registry, which is itself generated from the
course and self-checked by build_course_index.py.

Definition topics are excluded: they teach terminology and compute nothing. They remain in the
registry and seed the glossary.

Usage:
    python tools/build_frd.py [--check-only]
"""

from __future__ import annotations

import argparse
import sys
from collections import Counter, defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
REGISTRY = REPO / "registry" / "course_index.yml"
OUT = REPO / "docs" / "01-requirements" / "FRD.md"

EXCLUDED_CLAIM = "Definition"
LAYER_ORDER = ["Source Facts", "Derived Observations", "Decision Logic", "Trade Management"]
STAGE_ORDER = ["Context", "Candidate", "Setup", "Trigger", "Entry", "Risk",
               "Management", "Exit", "Review", "Validation"]


def load_rows() -> list[dict]:
    try:
        import yaml
    except ModuleNotFoundError:
        print("PyYAML required (pip install pyyaml)", file=sys.stderr)
        raise SystemExit(2) from None
    data = yaml.safe_load(REGISTRY.read_text(encoding="utf-8"))
    return data["topics"]


def render(rows: list[dict]) -> str:
    computable = [r for r in rows if r["claim_type"] != EXCLUDED_CLAIM]
    by_layer: dict[str, list[dict]] = defaultdict(list)
    for row in computable:
        by_layer[row["layer"]].append(row)

    claims = Counter(r["claim_type"] for r in computable)
    stages = Counter(r["stage"] for r in computable)
    charts = sum(1 for r in computable if r["chart_required"])

    out: list[str] = [
        "# FRD — functional requirements",
        "",
        "**Status:** generated · **Tier:** 1 (requirements)",
        "**Generated by:** `tools/build_frd.py` from `registry/course_index.yml` — **do not edit by hand.**",
        "",
        "Each row is a functional requirement keyed by its course component id. The id is the "
        "requirement id: tests cite it, the component registry keys on it, and the traceability "
        "check (`CI_POLICY.md` gate 10) fails on an orphan in either direction.",
        "",
        f"`Definition` topics are excluded — they teach terminology and compute nothing. "
        f"{len(rows) - len(computable)} of {len(rows)} topics are excluded on that basis.",
        "",
        "## Summary",
        "",
        f"**{len(computable)} functional requirements.**",
        "",
        "| Claim type | Count |",
        "|---|---|",
    ]
    for claim, count in claims.most_common():
        out.append(f"| `{claim}` | {count} |")
    out += [
        "",
        "| Lifecycle stage | Count |",
        "|---|---|",
    ]
    for stage in STAGE_ORDER:
        if stages.get(stage):
            out.append(f"| `{stage}` | {stages[stage]} |")
    out += [
        "",
        f"**{charts}** of these require a rendered chart (`CHART_SPEC.md`).",
        "",
        "**Every requirement below carries validation status `Untested` or `Not Applicable`.** "
        "None is validated, and none may be presented as such "
        "(`COMPONENT_REGISTRY_SPEC.md` §3). Satisfying a requirement means the component computes "
        "what its spec says — not that it works as a trading rule.",
        "",
    ]

    for layer in LAYER_ORDER:
        items = by_layer.get(layer)
        if not items:
            continue
        out += [f"## Layer — {layer}", "", f"{len(items)} requirements.", ""]
        by_module: dict[int, list[dict]] = defaultdict(list)
        for row in items:
            by_module[row["source_number"]].append(row)
        for module in sorted(by_module):
            group = sorted(by_module[module], key=lambda r: r["topic"])
            kind = group[0]["kind"]
            label = f"Module {module:02d}" if kind == "module" else f"Appendix {module}"
            out += [
                f"### {label}",
                "",
                "| Requirement | Title | Stage | Claim | Chart |",
                "|---|---|---|---|---|",
            ]
            for row in group:
                chart = "yes" if row["chart_required"] else ""
                title = row["title"].replace("|", "\\|")
                out.append(
                    f"| `{row['component']}` | {title} | {row['stage']} | {row['claim_type']} | {chart} |"
                )
            out.append("")

    out += [
        "## Note on scope",
        "",
        "This lists what the course *defines*, not what v1 *activates*. Owner decision D2 covers the "
        "full catalogue, satisfied at `registered` — which costs nothing. A requirement reaching "
        "`specified` needs an algorithm spec and declared parameters; reaching `active` additionally "
        "needs parameter values with provenance and golden vectors "
        "(`COMPONENT_REGISTRY_SPEC.md` §3).",
        "",
    ]
    return "\n".join(out) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check-only", action="store_true",
                        help="fail if the generated content differs from the file on disk")
    args = parser.parse_args()

    rows = load_rows()
    content = render(rows)
    computable = sum(1 for r in rows if r["claim_type"] != EXCLUDED_CLAIM)

    if args.check_only:
        if not OUT.is_file():
            print(f"FAIL: {OUT} does not exist", file=sys.stderr)
            return 1
        if OUT.read_text(encoding="utf-8") != content:
            print(f"FAIL: {OUT} is stale - regenerate with tools/build_frd.py", file=sys.stderr)
            return 1
        print(f"FRD current: {computable} requirements")
        return 0

    OUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUT}: {computable} requirements")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
