"""Generate docs/08-pm/COVERAGE_MATRIX.md from the registries.

Master ТЗ v1.0 §5 asks for a coverage matrix: area × documented / specified / implemented /
validated / runtime. Its own rule is that coverage may not be claimed without a formal basis, which
makes a hand-written matrix the worst possible form for it - the one document in the tree whose only
content is counts, maintained by hand, in a repository that has already shipped five documents
quoting a study count that was wrong.

So it is generated and gated, like the FRD and the component registry. Every cell is computed from
`registry/components.yml` and `registry/parameters.yml`; nothing here is authored, and a number that
looks wrong is a bug in this script or a fact about the tree, never a typo in a table.

The columns are a ladder, and each is strictly harder than the one before it:

  documented    a specification exists for the area
  specified     the component has an algorithm spec, declared parameters and listed consumers
  implemented   `implements` points at code that imports
  validated     the component's status is above `Untested`, or its parameter carries `validated:`
  runtime       activation is `active` - the component may be used in a decision

Usage:
    python tools/build_coverage.py [--check-only]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
COMPONENTS = REPO / "registry" / "components.yml"
PARAMETERS = REPO / "registry" / "parameters.yml"
DOCS = REPO / "docs"
OUT = REPO / "docs" / "08-pm" / "COVERAGE_MATRIX.md"

LAYER_ORDER = ["Source Facts", "Derived Observations", "Decision Logic", "Trade Management"]

#: Which specification carries each layer. Named rather than inferred: a document's existence is
#: the weakest column in the ladder, and guessing at it would make the weakest column also the
#: least trustworthy. Paths are checked, so a renamed document fails the gate.
LAYER_DOCS = {
    "Source Facts": ["03-data/POINT_IN_TIME_SPEC.md", "03-data/DATA_QUALITY_SPEC.md"],
    "Derived Observations": ["02-domain/ALGORITHM_SPEC.md", "02-domain/COMPONENT_REGISTRY_SPEC.md"],
    "Decision Logic": ["02-domain/RULE_SPEC.md", "02-domain/SCREENER_SPEC.md",
                       "02-domain/DECISION_STATE_MACHINE.md"],
    "Trade Management": ["02-domain/RISK_SPEC.md", "02-domain/EXIT_MODEL_SPEC.md",
                         "05-validation/EXECUTION_MODEL.md"],
}

#: Parameter namespaces grouped by the layer whose components consume them.
PARAMETER_LAYERS = {
    "Source Facts": ("data.", "universe."),
    "Derived Observations": ("atr.", "sma.", "pivot.", "regime.", "rs."),
    "Decision Logic": ("screen.", "watchlist."),
    "Trade Management": ("risk.", "exit.", "account.", "costs."),
}


def _load(path: Path):
    try:
        import yaml
    except ModuleNotFoundError:
        print("PyYAML required (pip install pyyaml)", file=sys.stderr)
        raise SystemExit(2) from None
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def _bar(part: int, whole: int, width: int = 10) -> str:
    """A fixed-width bar. Zero renders as an empty trough rather than as nothing."""
    if whole == 0:
        return "·" * width
    filled = round(width * part / whole)
    return "█" * filled + "·" * (width - filled)


def render(rows: list[dict], parameters: list[dict]) -> str:
    by_layer: dict[str, list[dict]] = {layer: [] for layer in LAYER_ORDER}
    for row in rows:
        by_layer.setdefault(row["layer"], []).append(row)

    out: list[str] = [
        "# COVERAGE MATRIX",
        "",
        "**Status:** generated · **Tier:** 8 (project management)",
        "**Generated by:** `tools/build_coverage.py` from `registry/components.yml` and "
        "`registry/parameters.yml` — **do not edit by hand.**",
        "",
        "Master ТЗ v1.0 §5. Its rule is that coverage may not be claimed without a formal basis, so "
        "every cell here is counted from a registry rather than asserted. The columns are a ladder "
        "and each rung is strictly harder than the one below it.",
        "",
        "| Column | Means |",
        "|---|---|",
        "| documented | a specification exists for the area |",
        "| specified | algorithm spec written, parameters declared with provenance, consumers listed |",
        "| implemented | `implements` resolves to code |",
        "| validated | status above `Untested`, or the parameter carries `validated:` |",
        "| **runtime** | activation is `active` — usable in a decision |",
        "",
        "## 1. By layer",
        "",
        "| Layer | Registered | Specified | Implemented | Validated | **Runtime** | Docs |",
        "|---|---:|---:|---:|---:|---:|---|",
    ]

    totals = dict.fromkeys(("registered", "specified", "implemented", "validated", "runtime"), 0)
    for layer in LAYER_ORDER:
        members = by_layer.get(layer, [])
        registered = len(members)
        specified = sum(1 for r in members if r.get("activation") in ("specified", "active"))
        implemented = sum(1 for r in members if r.get("implements"))
        validated = sum(1 for r in members if r.get("validation") not in
                        (None, "Untested", "Not Applicable"))
        runtime = sum(1 for r in members if r.get("activation") == "active")

        totals["registered"] += registered
        totals["specified"] += specified
        totals["implemented"] += implemented
        totals["validated"] += validated
        totals["runtime"] += runtime

        present = [d for d in LAYER_DOCS.get(layer, []) if (DOCS / d).is_file()]
        docs_cell = f"{len(present)} of {len(LAYER_DOCS.get(layer, []))}"
        out.append(
            f"| {layer} | {registered} | {specified} | {implemented} | {validated} | "
            f"**{runtime}** | {docs_cell} |"
        )

    out.append(
        f"| **Total** | **{totals['registered']}** | {totals['specified']} | "
        f"{totals['implemented']} | {totals['validated']} | **{totals['runtime']}** | |"
    )
    out += [
        "",
        "```",
        f"registered   {_bar(totals['registered'], totals['registered'])}  "
        f"{totals['registered']:>4}",
        f"specified    {_bar(totals['specified'], totals['registered'])}  {totals['specified']:>4}",
        f"implemented  {_bar(totals['implemented'], totals['registered'])}  "
        f"{totals['implemented']:>4}",
        f"validated    {_bar(totals['validated'], totals['registered'])}  {totals['validated']:>4}",
        f"runtime      {_bar(totals['runtime'], totals['registered'])}  {totals['runtime']:>4}",
        "```",
        "",
    ]

    # --- parameters -------------------------------------------------------------------
    by_status: dict[str, int] = {}
    for entry in parameters:
        by_status[entry.get("status", "?")] = by_status.get(entry.get("status", "?"), 0) + 1

    out += [
        "## 2. Parameters, by the layer that consumes them",
        "",
        "A parameter with no value makes its component refuse, so an `unset` count is a measure of "
        "how much of an area is deliberately inert rather than a backlog "
        "(`PARAMETER_REGISTRY.md` §4).",
        "",
        "| Layer | Parameters | Set | Unset | Validated |",
        "|---|---:|---:|---:|---:|",
    ]
    claimed = 0
    for layer in LAYER_ORDER:
        prefixes = PARAMETER_LAYERS.get(layer, ())
        members = [e for e in parameters if e["id"].startswith(prefixes)]
        claimed += len(members)
        settled = sum(1 for e in members if e.get("value") is not None)
        validated = sum(1 for e in members
                        if str(e.get("provenance") or "").startswith("validated:"))
        out.append(
            f"| {layer} | {len(members)} | {settled} | {len(members) - settled} | {validated} |"
        )

    layered = tuple(p for prefixes in PARAMETER_LAYERS.values() for p in prefixes)
    unclaimed = [e for e in parameters if not e["id"].startswith(layered)]
    unclaimed_set = sum(1 for e in unclaimed if e.get("value") is not None)
    unclaimed_validated = sum(
        1 for e in unclaimed if str(e.get("provenance") or "").startswith("validated:")
    )
    out += [
        f"| *(programme-level)* | {len(unclaimed)} | {unclaimed_set} | "
        f"{len(unclaimed) - unclaimed_set} | {unclaimed_validated} |",
        "",
        "Programme-level parameters (`validation.*`, `stats.*`) govern the validation programme "
        "rather than a component, so they have no layer.",
        "",
        "| Status | Count |",
        "|---|---:|",
    ]
    for status in ("unset", "assumed", "owner", "validated"):
        out.append(f"| `{status}` | {by_status.get(status, 0)} |")

    out += [
        "",
        "## 3. How to read the runtime column",
        "",
        "**It is zero, and that is the design rather than a gap.** A component reaches `active` only "
        "when its parameters have values, its verification exists and `implements` points at real "
        "code (`COMPONENT_REGISTRY_SPEC.md` §3). Components blocked by an `unset` parameter refuse "
        "rather than defaulting, which is the fail-closed rule working as specified.",
        "",
        "What the column is for is the gap between it and the one to its left: **implemented and not "
        "runtime** is the population where code exists that nothing may yet rely on. Watch that "
        "difference rather than the absolute number.",
        "",
        "## 4. What this matrix does not measure",
        "",
        "Stated because a coverage matrix invites over-reading, and the ТЗ's own rule is that "
        "coverage is not claimable without basis:",
        "",
        "- **Documented counts documents, not quality.** A specification that exists and is wrong "
        "scores the same as one that is right. Gate 3e checks that references resolve; nothing "
        "checks that a claim is true.",
        "- **Validated counts a status, not an edge.** `COMPONENT_REGISTRY_SPEC.md` §4 transcribes "
        "the course on this: validation statuses are not grades.",
        "- **Registered is free.** Every non-Definition course topic has a row by construction "
        "(owner decision D2), so the first column measures the course's size, not this project's.",
        "",
    ]
    return "\n".join(out) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check-only", action="store_true",
                        help="fail if the generated content differs from the file on disk")
    args = parser.parse_args()

    rows = (_load(COMPONENTS) or {}).get("components") or []
    parameters = (_load(PARAMETERS) or {}).get("parameters") or []
    content = render(rows, parameters)
    active = sum(1 for r in rows if r.get("activation") == "active")

    if args.check_only:
        if not OUT.is_file():
            print(f"FAIL: {OUT} does not exist", file=sys.stderr)
            return 1
        if OUT.read_text(encoding="utf-8") != content:
            print(f"FAIL: {OUT} is stale - regenerate with tools/build_coverage.py",
                  file=sys.stderr)
            return 1
        print(f"coverage matrix current: {len(rows)} components, {active} at runtime")
        return 0

    OUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUT}: {len(rows)} components, {len(parameters)} parameters, {active} at runtime")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
