"""Generate `requirements-lock.txt` - the transitive closure of what this project declares.

The file this replaces held **8 entries against 56 installed distributions**, was referenced by
nothing, and omitted `pandas-market-calendars`, which has been a declared runtime dependency since
2026-08-02. A lock nobody installs from and that names a seventh of the environment is not a lock;
it is a reproducibility claim with nothing behind it.

**Derived, not frozen.** `pip freeze` and this script agreed exactly on 2026-08-10 - both produced
the same 56 - so the choice was not made on today's output. It was made because `.venv` lives in
the main checkout and is shared by every worktree (HANDOFF section 8): a freeze locks whatever is
installed, and the first tool someone pip-installs into that shared environment for an unrelated
reason silently becomes a pinned dependency of this project. A walk from the declarations cannot
acquire one.

Worth recording, because the guess was wrong and checking was cheap: `ast-serialize`, `librt`,
`peewee` and `protobuf` looked like exactly that kind of contamination and are not. They are
required by `mypy` and by `yfinance` respectively, and they belong in the lock.

So the closure is walked from `pyproject.toml`'s own declarations instead, and pinned at the
versions installed in the environment doing the walking.

**Markers are handled by not handling them.** Evaluating `python_version < "3.11"` or
`platform_system == "Darwin"` properly needs `packaging`, which is not a declared dependency and
would be a strange thing to require of the tool that computes dependencies. Instead a requirement
is kept only if it resolves to an *installed* distribution: in a working environment, a requirement
excluded by its own marker is simply absent, so the environment answers the question the parser
would have had to. Requirements guarded by `extra == "..."` are skipped outright - those are the
optional faces of a dependency and nothing here requests them.

This means the lock is only as correct as the environment it is generated from, which is the same
contract every other generated registry here has: `--check-only` is the gate, and it fails if the
committed file no longer matches what the declarations resolve to.

    python tools/build_lock.py [--check-only] [--out PATH]
"""

from __future__ import annotations

import argparse
import os
import sys
import tomllib
from collections import deque
from importlib import metadata
from pathlib import Path

REPO = Path(os.environ.get("SWINGDESK_ROOT") or Path(__file__).resolve().parents[1])
PYPROJECT = REPO / "pyproject.toml"
DEFAULT_OUT = REPO / "requirements-lock.txt"

HEADER = (
    "# GENERATED by tools/build_lock.py - do not hand-edit.\n"
    "# The transitive closure of [project.dependencies] and [project.optional-dependencies].dev,\n"
    "# pinned at the versions the generating environment resolved. Regenerate after changing a\n"
    "# declaration; `--check-only` is gate 18 and will fail if this drifts.\n"
)

_NAME_END = "<>=!~[ ;("


def canonical(name: str) -> str:
    return name.strip().lower().replace("_", "-")


def requirement_name(requirement: str) -> str:
    for index, character in enumerate(requirement):
        if character in _NAME_END:
            return requirement[:index].strip()
    return requirement.strip()


def roots() -> list[str]:
    """Declared runtime dependencies plus the `dev` extra - everything a gate run needs."""
    with PYPROJECT.open("rb") as handle:
        config = tomllib.load(handle)
    project = config.get("project", {})
    declared = list(project.get("dependencies", []))
    declared += list(project.get("optional-dependencies", {}).get("dev", []))
    return [requirement_name(item) for item in declared]


def closure(names: list[str]) -> dict[str, str]:
    """{distribution: version} for `names` and everything they transitively require."""
    resolved: dict[str, str] = {}
    seen: set[str] = set()
    queue = deque(canonical(name) for name in names)

    while queue:
        name = queue.popleft()
        if name in seen:
            continue
        seen.add(name)
        try:
            dist = metadata.distribution(name)
        except metadata.PackageNotFoundError:
            # Not installed here. Either a marker excluded it or the environment is incomplete;
            # `tools/preflight.py` is what distinguishes those, and it runs first.
            continue
        resolved[canonical(dist.metadata["Name"])] = dist.version
        for requirement in dist.requires or []:
            if "extra ==" in requirement:
                continue
            queue.append(canonical(requirement_name(requirement)))
    return resolved


def render(pins: dict[str, str]) -> str:
    lines = [f"{name}=={version}" for name, version in sorted(pins.items())]
    return HEADER + "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--check-only", action="store_true",
                        help="fail if the committed lock differs from what the declarations resolve to")
    args = parser.parse_args()

    pins = closure(roots())
    if not pins:
        print("no declared dependency resolved; is anything installed?", file=sys.stderr)
        return 1
    rendered = render(pins)

    if args.check_only:
        if not args.out.exists():
            print(f"{args.out.name} is missing; run tools/build_lock.py", file=sys.stderr)
            return 1
        current = args.out.read_text(encoding="utf-8")
        if current != rendered:
            print(f"{args.out.name} is stale. Regenerate with: python tools/build_lock.py",
                  file=sys.stderr)
            current_pins = {
                line.split("==")[0]: line.split("==")[1]
                for line in current.splitlines() if "==" in line and not line.startswith("#")
            }
            for name in sorted(set(pins) - set(current_pins)):
                print(f"  missing from lock: {name}=={pins[name]}", file=sys.stderr)
            for name in sorted(set(current_pins) - set(pins)):
                print(f"  in lock but not required: {name}", file=sys.stderr)
            for name in sorted(set(pins) & set(current_pins)):
                if pins[name] != current_pins[name]:
                    print(f"  version moved: {name} {current_pins[name]} -> {pins[name]}",
                          file=sys.stderr)
            return 1
        print(f"lock current: {len(pins)} pinned")
        return 0

    args.out.write_text(rendered, encoding="utf-8")
    # Not `relative_to(REPO)`: --out is allowed to point outside the tree, and a test does exactly
    # that. Reporting the path must not be the thing that fails.
    print(f"wrote {args.out}: {len(pins)} pinned")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
