"""Gate 24: `HANDOFF.md` section 2's state block, generated rather than typed.

`AGENTS.md` §10.5 gave every measured count exactly one owner and gate 14 enforces it. That removed
the duplicate copies; it did not make the survivor true, because the survivor was typed by hand.

MEASURED 2026-08-15, which is what paid for this tool. HANDOFF §2's Track A row read *"counter at
3"* while `tools/track_a_streak.py` computed 4 - and the row described itself as *"computed by
`tools/track_a_streak.py` ... not hand-kept"*. The same table's directory row read *9 pulls, 1
confirmed* against a store holding 10 and 2. Both numbers sat in their single owner, both were
wrong, and nothing in the tree contradicted them. Concentrating a fact makes it findable, not true.

So section 2 is now generated between markers and `--check-only` is its gate - the same shape as
`build_frd.py`, `build_components.py`, `build_checklists.py`, `build_coverage.py` and
`build_lock.py`, none of which has ever gone stale.

**Three blocks.** Repo facts derive from the tree and are computable in every checkout. Runtime
facts derive from `data/`, which is gitignored operational state present only in the main checkout.
Splitting them is what lets `--check-only` verify the half it can see and report the other half as
`UNAVAILABLE` rather than either failing every worktree or - the gate 23 mistake this tool exists to
stop repeating - exiting 0 as though it had checked. The third, worktrees, is its own case: computable
everywhere like repo facts, but it is a LIST, not a census table, and it answers a different
question - not "what does the tree measure" but "who else is standing in a copy of it right now".

**The worktree block replaced a hand-typed table on 2026-08-16, for the same reason section 2 did.**
That table grew one row per effort, forever, with "what it holds" prose no tool could check - and it
required every session to remember to add its own row before its gates would pass. `git worktree
list` already knows which worktrees exist without being told. History belongs in `git log` and
`docs/08-pm/POSTMORTEM-2026-08-09.md`, which already carry it; a document a fresh session reads in
its first minute does not need to carry it twice.

Nothing here re-derives a number another tool already owns. The census comes from
`verify_counts.measure()`, the streak from `track_a_streak.measure()`, and the worktree list from
`verify_branches.worktree_branches()` - so gate 14, gate 16, gate 23 and this gate cannot disagree:
there is one implementation per fact.

Facts that no tool can derive - `master`'s branch protection, the Task Scheduler trigger, the G0-G7
project gates - stay hand-written BELOW the generated blocks, each carrying its own `as of` date.
That boundary is the honest one: generate what is derivable, date what is not, and never let the
second kind look like the first.

Needs PyYAML, pytest and duckdb, so it runs with the project venv.

    python tools/build_state.py                # rewrite the blocks in place
    python tools/build_state.py --check-only   # gate 24
"""

from __future__ import annotations

import argparse
import os
import sys
from datetime import UTC, datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

_ROOT_OVERRIDE = os.environ.get("SWINGDESK_ROOT")
REPO = Path(_ROOT_OVERRIDE or Path(__file__).resolve().parents[1])
HANDOFF = REPO / "HANDOFF.md"

#: The runtime stores. Overridable because several worktrees at once is this project's normal mode
#: (`HANDOFF.md` §2) and `data/` exists only in the main checkout - so a worktree that wants to
#: regenerate the runtime block points here rather than copying 228MB or hand-typing the result,
#: which is the failure this whole tool exists to end. There is one machine and one set of stores,
#: so pointing at them from a sibling tree reads the same facts, not different ones.
#:
#: Ignored when `SWINGDESK_ROOT` is pinned - a pinned root describes a complete tree, and a looser
#: variable must not reach outside it. Same ordering as `track_a_streak.py`, for the same reason.
DATA = Path(
    os.environ["SWINGDESK_DATA"]
    if os.environ.get("SWINGDESK_DATA") and not _ROOT_OVERRIDE
    else REPO / "data"
)

REPO_BEGIN = "<!-- BEGIN GENERATED: state:repo -->"
REPO_END = "<!-- END GENERATED: state:repo -->"
RUNTIME_BEGIN = "<!-- BEGIN GENERATED: state:runtime -->"
RUNTIME_END = "<!-- END GENERATED: state:runtime -->"
WORKTREES_BEGIN = "<!-- BEGIN GENERATED: state:worktrees -->"
WORKTREES_END = "<!-- END GENERATED: state:worktrees -->"

#: Exit code meaning "my subject is not present in this environment" (`check_gates.py`).
UNAVAILABLE_EXIT = 4

GENERATED_NOTE = (
    "*Generated by `tools/build_state.py` (gate 24). Do not edit between the markers - "
    "an edit here is overwritten and fails the gate.*"
)


# --------------------------------------------------------------------------- repo facts


def _studies() -> tuple[int, int]:
    """(registered, reported). A pre-registration is a `PR-*.md`; a report is its result page."""
    prereg = REPO / "docs" / "prereg"
    registered = len([p for p in prereg.glob("PR-*.md") if p.is_file()])
    reported = len(list((prereg / "results").glob("PR-*-report.md")))
    return registered, reported


def _criteria_version() -> str:
    import yaml

    document = yaml.safe_load((REPO / "registry" / "criteria.yml").read_text(encoding="utf-8"))
    return str(document.get("version", "unknown"))


def repo_rows() -> list[tuple[str, str]]:
    """Every fact derivable from the tree alone, in the order section 2 has always listed them."""
    from verify_counts import measure

    counts = measure()
    registered, reported = _studies()
    tests = counts.get("tests")

    return [
        ("Merge gates", f"**{counts['gates']}**, one command: `python tools/check_gates.py`"),
        ("Tests", f"**{tests}**, fully offline" if tests is not None
         else "UNAVAILABLE - pytest could not collect"),
        ("Docs", f"{counts['documents']} files, Tier 0-8 · indexed by `registry/project_manifest.yml`"),
        ("Components", f"{counts['components']} catalogued · {counts['components:registered']} "
                       f"registered · {counts['components:specified']} `specified` · "
                       f"**{counts['components:active']} `active`**"),
        ("Parameters", f"{counts['parameters']} - {counts['parameters:unset']} `unset`, "
                       f"{counts['parameters:assumed']} `assumed`, {counts['parameters:owner']} "
                       f"`owner`, **{counts['parameters:validated']} `validated`**"),
        ("Golden vectors", f"{counts['golden vectors']} vectors across "
                           f"{counts['golden components']} components"),
        ("Studies", f"{registered} registered · {reported} reported"),
        ("Criteria", f"`registry/criteria.yml` **v{_criteria_version()}**"),
    ]


def worktree_rows() -> list[tuple[str, str]]:
    """Every worktree currently checked out - not history, and never typed by hand.

    Reuses `verify_branches.py`'s own detection, so gate 16 (which checks that each branch name
    appears somewhere in this file) and this block can never disagree about what "currently checked
    out" means. A worktree whose directory now holds a different branch, or whose branch merged and
    was cleaned up, simply stops appearing - which is the point. There is no "what it holds" column:
    that was prose no tool could check, and it lived in the one document a fresh session reads before
    it has any of its own context to check it against. The commit history that produced each branch
    already says what it held, in more detail than a table cell ever could.
    """
    from verify_branches import merged_branches, worktree_branches

    branches = worktree_branches()
    merged = merged_branches()

    rows: list[tuple[str, str]] = []
    for branch, sha in branches:
        if merged is None:
            state = "merge state unknown - no `master` ref in this clone"
        elif branch in merged:
            state = "merged into `master`"
        else:
            state = "**NOT merged**"
        rows.append((f"`{branch}`", f"tip `{sha}` · {state}"))
    return rows


# ------------------------------------------------------------------------ runtime facts


def _connect(name: str):
    """Read-only handle. Never opened for write: this tool reports state, it never changes it."""
    import duckdb

    return duckdb.connect(str(DATA / name), read_only=True)


def _journal_facts() -> list[tuple[str, str]]:
    connection = _connect("journal.duckdb")
    try:
        runs = connection.execute("SELECT COUNT(*) FROM runs").fetchone()[0]
        dirty = connection.execute("SELECT COUNT(*) FROM runs WHERE code_dirty").fetchone()[0]
        open_runs = connection.execute(
            "SELECT COUNT(*) FROM runs WHERE completed_at IS NULL"
        ).fetchone()[0]
        decisions = connection.execute("SELECT COUNT(*) FROM decisions").fetchone()[0]
        uncoded = connection.execute(
            "SELECT COUNT(*) FROM decisions "
            "WHERE decision = 'Skip' AND (reason_code IS NULL OR reason_code = '')"
        ).fetchone()[0]
    finally:
        connection.close()
    return [
        ("Journal", f"{runs} runs, {open_runs} incomplete · **{dirty} run(s) recorded against a "
                    f"dirty tree** and therefore not replayable from their SHA"),
        ("Decisions", f"{decisions} recorded · {uncoded} uncoded refusals "
                      f"(`a.no_uncoded_failures` requires 0)"),
    ]


def _bar_facts() -> tuple[list[tuple[str, str]], int]:
    """Store size and the point-in-time integrity check, plus the instrument count for coverage.

    The integrity row is the one to read first. `scan --as-of` pins the clock and still fetches
    fresh, so it can write a bar whose `event_time` postdates the `knowledge_time` it was stored
    under - a fact from the future, readable by a decision dated before it. The query is cheap and
    the answer must be 0 forever; carrying it here turns a one-off forensic check into a standing
    measurement.
    """
    connection = _connect("bars.duckdb")
    try:
        rows = connection.execute("SELECT COUNT(*) FROM bars").fetchone()[0]
        instruments = connection.execute(
            "SELECT COUNT(DISTINCT instrument_id) FROM bars"
        ).fetchone()[0]
        violations = connection.execute(
            "SELECT COUNT(*) FROM bars WHERE event_time > knowledge_time"
        ).fetchone()[0]
    finally:
        connection.close()
    verdict = "**CLEAN**" if violations == 0 else f"**{violations} VIOLATION(S)**"
    return [
        ("Bar store", f"{rows:,} rows across {instruments:,} instruments"),
        ("PIT integrity", f"{verdict} - bars whose `event_time` postdates their `knowledge_time`: "
                          f"{violations}"),
    ], instruments


def _directory_facts(measured_instruments: int) -> list[tuple[str, str]]:
    connection = _connect("directory.duckdb")
    try:
        pulls = connection.execute(
            "SELECT COUNT(DISTINCT knowledge_time) FROM directory_pulls"
        ).fetchone()[0]
        confirmed = connection.execute(
            "SELECT COUNT(DISTINCT knowledge_time) FROM directory_pulls "
            "WHERE source_session_date IS NOT NULL"
        ).fetchone()[0]
        latest = connection.execute(
            "SELECT rows FROM directory_pulls ORDER BY knowledge_time DESC LIMIT 1"
        ).fetchone()
    finally:
        connection.close()
    listed = int(latest[0]) if latest else 0
    coverage = f"{measured_instruments / listed:.1%}" if listed else "n/a"
    return [
        ("Directory", f"**{pulls} pulls** · **{confirmed} confirmed** against the response's own "
                      f"`Last-Modified` (`source_session_date`); the rest predate the field and "
                      f"stay permanently unattributed (`DR-008` c3)"),
        ("Universe coverage", f"bars stored for {measured_instruments:,} of {listed:,} listed "
                              f"symbols - **{coverage}**"),
    ]


def _track_a_row() -> tuple[str, str]:
    """The streak, taken from gate 23's own measurement rather than recomputed.

    Two implementations of one number is how the number this tool exists to fix went wrong in the
    first place.
    """
    from track_a_streak import TARGET_STREAK, measure

    reading = measure()
    if reading is None:
        return ("Track A clock", "UNAVAILABLE - no `data/daily_run.log` in this checkout")
    body = f"**{reading.count}/{TARGET_STREAK}** consecutive clean sessions"
    if reading.count and reading.start and reading.end:
        body += f" ({reading.start} to {reading.end})"
    if reading.broke_at is not None:
        body += f" · most recent break {reading.broke_at}"
    return ("Track A clock", body + " · `a.run_completes`, computed by `tools/track_a_streak.py`")


def runtime_rows() -> list[tuple[str, str]] | None:
    """Facts from `data/`, or None when this checkout has no local store.

    None is not an error and not an empty result. It is the third state: the subject of the
    measurement is absent here, so no claim about it can be made from this tree.
    """
    if not DATA.is_dir():
        return None
    bar_rows, instruments = _bar_facts()
    return [*_journal_facts(), *bar_rows, *_directory_facts(instruments), _track_a_row()]


# ----------------------------------------------------------------------------- rendering


def _table(rows: list[tuple[str, str]]) -> str:
    body = "\n".join(f"| {label} | {value} |" for label, value in rows)
    return f"| | |\n|---|---|\n{body}"


def render_repo() -> str:
    return f"{REPO_BEGIN}\n\n{GENERATED_NOTE}\n\n{_table(repo_rows())}\n\n{REPO_END}"


def render_worktrees() -> str:
    rows = worktree_rows()
    if rows:
        header = "| Branch | State |\n|---|---|"
        body = header + "\n" + "\n".join(f"| {label} | {value} |" for label, value in rows)
    else:
        body = "*No other worktree is currently checked out.*"
    return f"{WORKTREES_BEGIN}\n\n{GENERATED_NOTE}\n\n{body}\n\n{WORKTREES_END}"


def render_runtime(rows: list[tuple[str, str]] | None) -> str:
    if rows is None:
        body = (
            "> **UNAVAILABLE in this checkout.** These figures derive from `data/`, which is "
            "gitignored operational state and exists only in the main checkout. Regenerate there:\n"
            "> `python tools/build_state.py`"
        )
    else:
        stamp = datetime.now(UTC).strftime("%Y-%m-%d")
        body = f"{_table(rows)}\n\n*Measured from `data/` on {stamp}.*"
    return f"{RUNTIME_BEGIN}\n\n{body}\n\n{RUNTIME_END}"


def _replace(text: str, begin: str, end: str, body: str) -> str:
    start = text.find(begin)
    stop = text.find(end)
    if start == -1 or stop == -1 or stop < start:
        raise LookupError(f"{HANDOFF.name} is missing the {begin!r} / {end!r} markers")
    return text[:start] + body + text[stop + len(end):]


def main() -> int:
    parser = argparse.ArgumentParser(prog="build_state")
    parser.add_argument("--check-only", action="store_true",
                        help="fail if the committed blocks differ from what the tree measures")
    args = parser.parse_args()

    original = HANDOFF.read_text(encoding="utf-8")
    runtime = runtime_rows()

    updated = _replace(original, REPO_BEGIN, REPO_END, render_repo())
    updated = _replace(updated, WORKTREES_BEGIN, WORKTREES_END, render_worktrees())
    if runtime is not None:
        updated = _replace(updated, RUNTIME_BEGIN, RUNTIME_END, render_runtime(runtime))

    if not args.check_only:
        HANDOFF.write_text(updated, encoding="utf-8")
        scope = "repo + runtime" if runtime is not None else "repo only (no local data/)"
        print(f"state: wrote {HANDOFF.name} section 2 ({scope})")
        return 0

    if updated != original:
        print(f"state: {HANDOFF.name} section 2 is stale. Regenerate:")
        print("  python tools/build_state.py")
        return 1

    if runtime is None:
        # The repo half verified; the runtime half could not be read here. Saying so is the whole
        # point - gate 23 returned 0 in exactly this situation and a hand-kept counter went
        # uncontradicted for days (`AGENTS.md` §10.6).
        print("state: repo block current; runtime block UNAVAILABLE (no local data/ in this checkout)")
        return UNAVAILABLE_EXIT

    print("state: section 2 current (repo + runtime)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
